name: upload my image to DockerHub

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: docker build --tag oopsify .

      - name: Run Docker
        run: docker run -d --name app -p 80:4173 oopsify

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install software
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run Selenium script
        run: python main_tests.py